### ISSUE TITLE
dbt 0.19.0rc1 introduced breaking change to SQLConnectionManager

### ISSUE THREAD

**Issue by davidcmh** [tglunde/dbt-exasol#10]
dbt version 0.19.0rc1 introduced a breaking change to the SQLConnectionManager class which causes the following error when using the dbt-exasol adapter:

```
Can't instantiate abstract class DremioConnectionManager with abstract methods get_response
```

A similar [issue](https://github.com/fabrice-etanchaud/dbt-dremio/issues/9) was also raised and addressed in `dbt-dremio`.

**Comment by tglunde** [comment]
thx for the note - we finally got to it - i'll work now with dbt-exasol 0.3.0 and dbt-0.19.x
