### ISSUE TITLE
--full-refresh handling differs from core (again)

### ISSUE THREAD

**Issue by johannes-becker-otto** [tglunde/dbt-exasol#105]
Hallo Torsten and Ilija,
I've been away from Exasol for the last 3 month and was checking out the changes in dbt exasol 1.5

I realized that the line
`{%- set full_refresh_mode = (should_full_refresh()  or existing_relation.is_view) -%}`
and its implications disappeared from the new incremental implementation.
https://github.com/tglunde/dbt-exasol/issues/60 

It's an important and generally in dbt implemented feature if you have tables that you REALLY want to prevent from being ever full-refreshed.

Given the additional changes it would mainly mean to replace
`{% set full_refresh_mode = flags.FULL_REFRESH %}`
with
`{% set full_refresh_mode = should_full_refresh() %}`

although it might come into place in other parts as well given how often should_full_refresh is used in dbt core
https://github.com/search?q=repo%3Adbt-labs%2Fdbt-core%20should_full_refresh&type=code

Let me know if I can be of any help (unlike in April I should even have some capacities...)

All the best
Hannes

**Comment by ilikutle** [comment]
Hello @johannes-becker-otto, 
we have submitted a PR #107 with a possible solution for this. Can you please retest it and let us know if everything works as expected. 
Thank you for contribution :)

**Comment by johannes-becker-otto** [comment]
Works, thank you :)

**Comment by tglunde** [comment]
Thx. Published with 1.5.1
