### ISSUE TITLE
session datetime format set to JSON

### ISSUE THREAD

**Issue by djamadeus** [tglunde/dbt-exasol#119]
in incremental models when we compare dates for the incremental clause we endup with this:

Exasol Query Error: data exception - invalid character value for cast; Value: '2024-03-19 01:02:27.095000' Format: 'YYYY-MM-DDTHH:MI:SS.FF6' (Session: 1793951975412989952)

I don't understand where the 'T' in expected format comes from. is there NLS_DATE_LANGUAGE soemwhere set in the adapter?

incremental clause:
```
    {% if is_incremental() %}

    {%- call statement('where_pushdown_for_virtual_schema_statement', fetch_result=True) -%}
        select max(PV_TIMESTAMP) from {{ this }}
    {%- endcall -%}

    {%- set max_date = load_result('where_pushdown_for_virtual_schema_statement')['data'][0][0] -%}

  -- this filter will only be applied on an incremental run
where PV_TIMESTAMP >= '{{ max_date }}'

    {% endif %}
```

I can fix this then by using to_char and re-formatting the date, but I don't understand where the JSON-Notation comes (on the side of the selected PV_TIMESTAMP, not the variable) in the first place

**Comment by djamadeus** [comment]
my bad, just found the timestamp parameter for the connection configuration in the readme, sry

**Comment by bharathktw** [comment]
@djamadeus 
In my exasol i have the time stamp values to `2024-11-27-07.12.30.136000`,
but I am receiving error similar to you .
can I know what is the solution you did?
I tried to update the `profile.uml` with `timestamp_format: 'YYYY-MM-DD-HH.MI.SS.FF6' configuration still receiving the error as 
 Exasol Query Error: data exception - invalid character value for cast; Value: '2200-01-01 00:00:00.001' Format: 'YYYY-MM-DD-HH.MI.SS.FF6' in cast of expression '2200-01-01 00:00:00.001' (Session: 1816909531021508622)

but not sure how to fix this issue

**Comment by djamadeus** [comment]
@bharathktw: your formatstring is wrong: 'YYYY-MM-DD**-**HH.MI.SS.FF6'  the minus between DD and HH should be a space I reckon
