### ISSUE TITLE
error "invalid protocol version v3"

### ISSUE THREAD

**Issue by jups23** [tglunde/dbt-exasol#16]
## Environment
- dbt-exasol 0.1.2
- dbt 0.21.0
- pyexasol 0.20.0
- Exasol 6

## How to reproduce
Running any dbt command which connects to Exasol, e.g. `dbt test` I get the following error:
```
> dbt test
```
> Found 36 models, 125 tests, 1 snapshot, 3 analyses, 413 macros, 0 operations, 0 seed files, 26 sources, 0 exposures
> Encountered an error:
Runtime Error
  v3 is not a valid protocol version.
  
  
 ## Proposed fixes
### Fix 1: remove "v" prefix
[The string constants specifying the protocol version in pyexasol](https://github.com/littleK0i/pyexasol/blob/master/pyexasol/constant.py#L1) seem to have a different format [than in dbt-exasol](https://github.com/tglunde/dbt-exasol/blob/master/dbt/adapters/exasol/relation.py#L16)

I concluded from my test that the prefix "v" has to be removed.

### Fix 2: make protocol_version configurable

Let users of Exasol 6 configure in their profiles.yml the protocol version which [dbt-exasol sets here](https://github.com/tglunde/dbt-exasol/blob/585ace5eea5ea02d13aac71bcceea373b39eeee6/dbt/adapters/exasol/connections.py#L39) 

I understand that Exasol 6 has reached its end of lifetime. However, I have to work with with Exasol 6.0.6 which does **not** support the automatic downgrade of the protocol version. Thus, when the connection is initialized with version "3" it throws an error. I have to set protocol version 1.

**Comment by jups23** [comment]
I'll submit a PR tomorrow which implements the outlined fixes above

**Comment by tglunde** [comment]
Hi, have you tried to just add "protocol_version" to the dbt profile? According to https://github.com/tglunde/dbt-exasol/blob/585ace5eea5ea02d13aac71bcceea373b39eeee6/dbt/adapters/exasol/connections.py#L55 the parameter should be read by dbt?

**Comment by jups23** [comment]
yes, it works then without my patch. Great! I was wondering how it could have worked for you :-)
