### ISSUE TITLE
pyexasol encryption attribute

### ISSUE THREAD

**Issue by johannes-becker-otto** [tglunde/dbt-exasol#18]
Hi,
I just got a friendly reminder from my admin that I should not connect to the database unencrypted.
If it's a quick thing for you to add it I'd be grateful.
Otherwise I'll try to add it as a profiles.yml attribute and write a PR (beginning of next week).
I guess it'll go somewhere around here:
```
C = connect(dsn=credentials.dsn, user=credentials.user,
                        password=credentials.password, **ecryption=credentials.encryption or False**, autocommit=True, protocol_version=protocol_version)
```
(I'm guessing a bit right now)
All the best
Hannes

**Comment by ilikutle** [comment]
Hello @johannes-becker-otto ,
Please feel free to submit a PR, we love to see it. Otherwise, we'll also get to it, but probably not so soon.

Kind regards!
Ilija

**Comment by johannes-becker-otto** [comment]
Hi,
just an FYI. I'm using my PR in tests and it works.
Best regards,
Hannes

**Comment by tglunde** [comment]
Hi. Merged! Thank you for your contribution!

**Comment by johannes-becker-otto** [comment]
Pleasure :)
