### ISSUE TITLE
--full-refresh handling differs from core

### ISSUE THREAD

**Issue by johannes-becker-otto** [tglunde/dbt-exasol#60]
Hi,
Today, I found two discrepancies between the exasol incremental implementation and the dbt core one

1. A failed --full-refresh in exasol leads to a dropped table
Core avoids this by doing a swap
  {% elif full_refresh_mode %}
      {% set build_sql = get_create_table_as_sql(False, intermediate_relation, sql) %}
      {% set need_swap = true %}
      (and then renaming and dropping if everything else works)
2. adding full_refresh=false or true to your config has no impact in Exasol
in core it's
{%- set full_refresh_mode = (should_full_refresh()  or existing_relation.is_view) -%}
and the should_full_refresh handles the config part
dbt exasol only checks
{%- set full_refresh_mode = (flags.FULL_REFRESH == True) -%}

I feel like the second point is an easy fix as should_full_refresh should be readily available from dbt core, so all it needs is to swap the columns.
The first point is a bit more intertwined.

If there aren't any open branches regarding incremental materilization I'd volunteer to try and fix these issues.

Cheers
Hannes

**Comment by tglunde** [comment]
Hi Hannes,
I was starting to work on the branch feature/38-incremental-materialization-strategies to actually get incremental materialilzation back into sync with core - but did not manage to commit anything. So please go ahead and fix your finding on that branch.
Thx a lot and any help is highly appreciated!

Regards, Torsten

**Comment by tglunde** [comment]
Hi @johannes-becker-otto ,
I changed our incremental model implementation back to re-use what is default in dbt-core. Pushed changes to https://github.com/tglunde/dbt-exasol/pull/62.
Could you double check, wether this changes the behaviour as expected?

Cheers, Torsten

**Comment by johannes-becker-otto** [comment]
Hi Torsten,
it should, I'll run the branch as soon as I find the time.
All the best
Hannes

**Comment by tglunde** [comment]
I will go ahead and close this issue for now - please feel free to re-open once you get testing it in failure. BR Torsten
