### ISSUE TITLE
Column-level comments in views cause ERROR when config.persist_docs is enabled

### ISSUE THREAD

**Issue by marvin-froemming** [tglunde/dbt-exasol#80]
As per Exasol documentation, view comments can only be specified in the CREATE VIEW statement. [(Source)](https://docs.exasol.com/db/7.0/sql/comment.htm#UsageNotes)

Unfortunately, this adapter currently tries to set the column comments _outside_ of the CREATE VIEW statement by using COMMENT IS after the DDL. While this works for tables, it will raise an error for views. It only happens if you provide column descriptions for a model in the YAML file. 

For example, the following statement is automatically generated by dbt and sent to Exasol if the columns are properly documented:

```
COMMENT ON view test_schema.test_view (
"test_col_1"  IS 'testtest',
"test_col_2"  IS 'testtest2'
)
```

Which will raise the following error: 
```
syntax error, unexpected '(', expecting IS_ or IS_NULL_
```

According to my tests this only applies to column-level comments, model comments work properly.

Pretty sure that [this macro](https://github.com/tglunde/dbt-exasol/blob/acae144e7a0ffa49656de8df922cf9ffd0cd8476/dbt/include/exasol/macros/adapters.sql#L149) just needs a check whether the relation is a view and if so, just omit the comments. But I haven't had time to fully understand whether comments are actually added twice (first in DDL and afterwards again). I'd be willing to submit a PR, but I have no prior experience contributing/testing a dbt adapter. 

**My setup:**

I enabled the `persist_docs` config in dbt_project.yml:
```
models:
  +persist_docs:
    columns: true
    relations: true
```

Used dbt version: 1.4.6
Used Exasol version: 7.1+

**Comment by tglunde** [comment]
Hi @marvin-froemming ,

thank you very much for the detailed description and clear error statement.
It should be an easy fix as described by you already - I will look into it this week. 
Please create a suggestion anyhow - even on a PR - I can join in and provide the testing efforts - or if you wish we could do it in pair.

Regards, Torsten
