### ISSUE TITLE
Some tests fail on Exasol 8 due to missing encryption argument

### ISSUE THREAD

**Issue by marvinfromblueforte** [tglunde/dbt-exasol#88]
We have a 100% passing rate when testing on Exasol 7. Tested on [docker-db 7.1.22](https://github.com/exasol/docker-db/releases/tag/7.1.22)

On Exasol 8, the passing rate is only 87%. Tested on [docker-db 8.21.0](https://github.com/exasol/docker-db/releases/tag/8.21.0).

There are two main issues:

1.) ExasolConnectionManager:
`message     =>  Connection exception - Only TLS connections are allowed.`

Some tests fail when there's a profiles.yml config that deviates from conftest.py. Pretty sure it's just the "encryption=True" which is missing, but seems to be required as of Exasol 8. We can just enable encryption by default in the adapter. If somebody still wants to disable it they can do it manually.

2.) Still gotta check another issue related to grants: test_grants.py > TestInvalidGrantsExasol. It throws an error as expected, but the test still fails.

**Comment by marvinfromblueforte** [comment]
The only remaining issue now is that, for some reason, Exasol 8 uses "TIMESTAMP(3)" instead of "TIMESTAMP" as a data type, which causes the TestDocsGenerateExasol and TestDocsGenReferencesExasol to fail. In other features like model contracts we bypassed this problem by cutting off the length indicator and only using TIMESTAMP, VARCHAR etc.

I haven't found a smart way yet to have the test pass both in Exasol 7 and 8 without rewriting the whole test. There should be a way to access the [.login_info](https://github.com/exasol/pyexasol/blob/master/docs/REFERENCE.md#login_info) (which includes the DB version) from pyexasol during the test, in which case I could simply have two -- one for each version -- and have the other one xfail or skip respectively.

**Comment by tglunde** [comment]
Hi @marvinfromblueforte ,
did you have any changes to commit regarding the connection issue and encryption=True. Regarding TIMESTAMP behaviour I think it is ok to just alternate the test behaviour depending on the Exasol version it is running on. 
Just let me know about the encryption and then we should be moving on with this?
Regards
