### ISSUE TITLE
support dbt_utils.dateadd function

### ISSUE THREAD

**Issue by jups23** [tglunde/dbt-exasol#9]
I tried to employ the test [dbt_utils.recency](https://github.com/fishtown-analytics/dbt-utils#recency-source) but the generated SQL causes a syntax error on Exasol. It seems that the `dbt_utils.dateadd()` macro is not implemented for dbt-exasol. I'd love to chat about how I can help to add it.

Here is the generated SQL output:
```
  select
      case when count(*) > 0 then 0
      else 1
      end as error_result
  from TABLE_NAME
  where created_at >=dateadd(day, -1, current_timestamp::timestamp)
```

dbt version: 0.18.1
dbt-exasol version: 0.2.0

**Comment by jwarlander** [comment]
Basically you need to put this in `macros/dateadd.sql` in your project:
```
{% macro exasol__dateadd(datepart, interval, from_date_or_timestamp) %}
    cast({{ from_date_or_timestamp }} as date) +  ((interval '1' {{ datepart }}) * ({{ interval }}))
{% endmacro %}
```

..and then add a variable config in `dbt_project.yml`:
```
vars:
  dbt_utils_dispatch_list: 
    - <your_project_name>
```

It would be useful to add this, and some other stuff, as a "shim" for Exasol though; I asked about it in the dbt Slack, and got some good hints on how to do that.. I may pull together the things we needed, at least for `date_spine` and dependencies :smile:

**Comment by jups23** [comment]
Thank you @jwarlander ! 
I'm getting a compilation error after `dbt clean && dbt deps`:

Running with dbt=0.18.1
Encountered an error:
Compilation Error in test dbt_utils_recency_fct_my_table_day__at_date__1 (models/mart/schema.yml)
  can only concatenate str (not "list") to str
  
  > in macro test_recency (macros/schema_tests/recency.sql)
  > called by macro _get_utils_namespaces (macros/cross_db_utils/_get_utils_namespaces.sql)
  > called by test dbt_utils_recency_fct_my_table_metrics_day__at_date__1 (models/mart/schema.yml)

**Comment by jups23** [comment]
I've found a workaround to have the same functionality by re-implementing this schema.

I created the file macros/schema_tests/test_recency.sql

```
{% macro test_recency(model, column_name='at_date') %}
	select
		case when count(*) > 0 then 0  -- success, we have recent data
			else 1 -- fail, we have no recent data
		end as error_result
	from {{ model }}
	where {{ column_name }} >= current_date() - 1
{% endmacro %}
```

Then, in schema.yml I configure
```
models:
    - name: my_name
      description: ""
      tests:
        - recency
```

Do you have any feedback on this implementation?

**Comment by jwarlander** [comment]
It doesn't quite seem the same as what's in the dbt-utils repo; that one has an interval parameter, etc.. Are you using the latest dbt-utils version? :) I noticed there were some bugfixes in January affecting test_recency (and a lot of other macros).

**Comment by jwarlander** [comment]
With my (fairly recent) install of dbt-utils (0.6.4), I do get an error, but another one entirely:

```
Runtime Error in test dbt_utils_recency_###__created_at__1 (models/staging/###.yml)
  
  (
      message     =>  syntax error, unexpected DOUBLE_COLON_ [line 14, column 22] (Session: ###)
      dsn         =>  ###:8563
      user        =>  ###
      schema      =>  
      session_id  =>  ###
      code        =>  42000
      query       =>  /* {"app": "dbt", "dbt_version": "0.18.1", "profile_name": "###", "target_name": "dev", "node_id": "test.###.dbt_utils_recency_###__created_at__1"} */
  
  
  
  
  select
      case when count(*) > 0 then 0
      else 1
      end as error_result
  from ###
  where created_at >=
      
      cast(
      current_timestamp::
      timestamp
  
   as date) +  ((interval '1' day) * (-1))
  )
```

**Comment by jwarlander** [comment]
Well, nice, that exposed a bug in my `dateadd()` macro :joy: 

So, the above error actually is due to having to implement `dbt_utils.current_timestamp()` for Exasol:
```
{% macro exasol__current_timestamp() %}
    current_timestamp
{% endmacro %}
```

..and then implement `dbt_utils.dateadd()` so it's more faithful to the original, casting to timestamp - not date:
```
{% macro exasol__dateadd(datepart, interval, from_date_or_timestamp) %}
    cast({{ from_date_or_timestamp }} as timestamp) +  ((interval '1' {{ datepart }}) * ({{ interval }}))
{% endmacro %}
```

After that, you should be able to simply use it:
```
models:
  - name: some_model
    tests:
      - dbt_utils.recency:
          datepart: day
          field: created_at
          interval: 1
```

**Comment by jups23** [comment]
Works like a charm! 

I have implemented an exasol version for `dbt_utils.surrogate_key`. Should I create a PR and add it to this dbt-exasol package?

**Comment by jwarlander** [comment]
The advice I got on the dbt Slack was to create a shim package specifically for the utils.. https://getdbt.slack.com/archives/C50NEBJGG/p1612455351024500

I haven't quite gotten to it, but intended to do so, as we had to implement a few of them (`current_timestamp`, `dateadd`, `datediff`, `generate_series`).

**Comment by jups23** [comment]
Great, I'll wait then for you to start the exasol shim package for dbt-utils. 

For the interest of people using Google I'll give my implementation of dbt_utils.surrogate_key for Exasol here:
```
{% macro exasol__surrogate_key(field_list) %}

{%- set fields = [] -%}

{%- for field in field_list -%}

    {%- set _ = fields.append(
        "coalesce(to_char(" ~ field ~ "), '')"
    ) -%}

    {%- if not loop.last %}
        {%- set _ = fields.append("'-'") -%}
    {%- endif -%}

{%- endfor -%}

hash_md5({{ dbt_utils.concat(fields) }})

{% endmacro %}
```
