### ISSUE TITLE
Source freshness on TIMESTAMP column fails

### ISSUE THREAD

**Issue by matchaEis** [tglunde/dbt-exasol#90]
First and foremost: thanks @tglunde and everybody else who is developing and supporting this adapter :)

we have definied a freshness of a source view
![image](https://github.com/tglunde/dbt-exasol/assets/57658168/272d3980-c657-4ead-b7f0-be28d4f8bb7f)
The column in the view is of type TIMESTAMP
![image](https://github.com/tglunde/dbt-exasol/assets/57658168/2d03893b-5acf-419b-86fa-b8a9cad43f34)
Running the source freshness tests results in an error
![image](https://github.com/tglunde/dbt-exasol/assets/57658168/fc44ea6e-b379-4e15-a98e-d802530f04b8)
We are using the newest version of dbt-exasol

Does anyone has an idea, why dbt thinks, that DWH_LOAD_STAMP is of type string?
Are we doing something wrong or is it a bug?

**Comment by tglunde** [comment]
Hi @matchaEis ,
thanks for opening the issue, we appreciate the feedback to improve our code.
Could you please check the dbt.log if you can find the statements causing this error? If possible just upload the log file.
Thx, Torsten

**Comment by matchaEis** [comment]
Hi @tglunde,
I should have uploaded the log file in the first place :)
[dbt.log](https://github.com/tglunde/dbt-exasol/files/12450760/dbt.log)

_select
      max(DWH_LOAD_STAMP) as max_loaded_at,
      current_timestamp() as snapshotted_at
    from DWH_SAP_P01.BKPF_

Thank you :) Max

**Comment by tglunde** [comment]
published in 1.4.5
